version: "3"
services:
  api:
    # Mendefinisikan atribut yang digunakan saat build container
    build:
      # Memberikan folder yang berisi dockerfile yang akan digunakan untuk build container 
      context: ./api
      dockerfile: Dockerfile
    # Mendefinisikan port yang digunakan oleh container
    ports:
      - "6000"
  etl:
    # Mendefinisikan atribut yang digunakan saat build container
    build:
      # Memberikan folder yang berisi dockerfile yang akan digunakan untuk build container
      context: ./etl
      dockerfile: Dockerfile
    # Menggunakan depends_on agar container etl jalan setelah container api
    depends_on:
      - api